version: '3'

name: siderdb

services:
  app:
    container_name: catalyst
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      - CATALYST_DEBUG=1
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=siderdb
    volumes:
      - .:/app
    networks:
      - app-tier
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:15.3
    restart: always
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=siderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-tier

volumes:
  db-data:

networks:
  app-tier:
