version: '3'

services:
  app:
    container_name: siderdb
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      - CATALYST_DEBUG=1
    volumes:
      - .:/app
    networks:
      - app-tier

networks:
  app-tier:
