schema_class: siderDB::Schema

resultsets:
- SuperPopulation
- Population

fixture_sets:
  basic:
    - SuperPopulation
    -
      -
        - id
        - code
        - description
        - timestamp
      -
        - 1
        - BRZ
        - Brazilians
        - 20231224
    - Population
    -
      -
        - super_population_id
        - id
        - code
        - description
        - timestamp
      -
        - 1
        - 1
        - ESP
        - Elderly Brazilians living in Sao Paulo
        - 20231224
