schema_class: siderDB::Schema

resultsets:
- SuperPopulation
- Population

fixture_sets:
  basic:
    - SuperPopulation
    -
      -
        - code
        - description
      -
        - BRZ
        - Brazilians
    - Population
    -
      -
        - code
        - super_population_code
        - description
      -
        - ESP
        - BRZ
        - Elderly Brazilians living in Sao Paulo
